### 上传文件
POST {{media_host}}/media/upload/coursefile
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="filedata"; filename="widget-timg.jpeg"
Content-Type: application/octet-stream

< d:/develop/upload/widget-timg.jpeg